### ISSUE TITLE
wavedrom not working with make latexpdf

### ISSUE THREAD

**Issue by oholimoli** [bavovanachte/sphinx-wavedrom#44] opened 2022-02-16 11:46 UTC
Hi, I'm using this extension to generate the html with Sphinx and everything works fine. When I try to generate a pdf with `make latexpdf` I get a timeout after 120sec.

Is this a bug in the extension?

**Comment by bavovanachte** [comment] 2022-02-16 12:27
Hi @oholimoli , do you have more details? An error log from latex perhaps? Or a minimal example that reproduces the issue?

**Comment by oholimoli** [comment] 2022-02-16 16:39
The std_out of make latexpdf stops at the message: "writing ..." my timeout is 120sec.  Sorry for not posting a complete example. Has latexpdf been working?

I will add a minimal example the next days.

**Comment by bavovanachte** [comment] 2022-02-16 18:59
No worries. Yes, latexpdf is included in the CI pipelines, so tested regularly (it's failing for py3.10, but that's a wavedrompy issue). 

How are you configuring the plugin? If you're not applying any configuration, the html build will use browser-rendered (js) images and the pdf will use wavedrom-cli. If that's the case, you might be facing the same issue as https://github.com/bavovanachte/sphinx-wavedrom/pull/43 (i.e. npx is waiting for user input and blocking the execution)

**Comment by oholimoli** [comment] 2022-02-17 08:45
I captured the output. I will try to install the missing font. @bavovanachte do you know which fonts are needed? Not sure if other fonts are missing too. I'm currently only running a minimal example.

```
! LaTeX Error: File `tgtermes.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

Enter file name: ^C! Interruption.
```

**Comment by oholimoli** [comment] 2022-02-17 09:29
In order to solve the problem with the missing fonts I made a new Docker base image: `sphinxdoc/sphinx-latexpdf:4.4.0`. It has python 3.10 :(. It looks like I am stuck with this problem now. Is there already a workaround available?

This is the error I get now:
```
Extension error:
Could not import extension sphinxcontrib.wavedrom (exception: No module named 'sphinxcontrib.wavedrom')
make: *** [Makefile:20: latexpdf] Error 1
```

**Comment by bavovanachte** [comment] 2022-02-28 21:29
Excellent, so now it's a duplicate of https://github.com/bavovanachte/sphinx-wavedrom/issues/38 (which is actually an issue of the wavedrom python implementation). Could you close this issue in favor of #38 ?

**Closed** 2022-03-07 20:57 UTC
